name: Has a valid Blueprint.json file?

on:
    pull_request:

jobs:
    check_blueprints:
        runs-on: ubuntu-latest

        env:
            GITHUB_BRANCH: ${{ github.ref }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Fetch trunk
              run: |
                  git fetch origin trunk

            - name: Install pre-requisites
              run: |
                  pip install -r requirements.txt

            - name: Run validate_pr.py
              run: |
                  python validate_pr.py
