name: Reindex Blueprints after changes

on:
  push:
    branches:
      - trunk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Run make_index.py
      run: python make_index.py
    - name: Check for uncommitted changes
      id: changes
      run: |
          if [ -z "$(git status --porcelain)" ]; then
              echo "No changes"
              echo 'CHANGES=0' >> $GITHUB_OUTPUT
          else
              echo "Changes detected"
              echo 'CHANGES=1' >> $GITHUB_OUTPUT
          fi
    - name: Push rebuilt WordPress to GitHub
      if: steps.changes.outputs.CHANGES == '1'
      run: |
          git config --global user.name "deployment_bot"
          git config --global user.email "deployment_bot@users.noreply.github.com"
          git remote set-url origin https://${{ secrets.GH_ACTOR }}:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
          git add -A
          git commit -a -m "Reindex Blueprints"
          git pull --rebase
          if [ $? -eq 0 ]; then
              git push origin HEAD:trunk
          fi;