name: Ships a valid Blueprint.json file?

on:
    pull_request:

jobs:
    check_blueprints:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Run validate_pr.py
              run: |
                  python validate_pr.py
